import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    height: "100%",
    backgroundColor: "white",
  },
  addContainer: {
    height: "100%",
    backgroundColor: "black",
    alignItems: "center",
  },
  section: {
    marginTop: 70,
  },
  item: {
    backgroundColor: "white",
    padding: 20,
    marginVertical: 8,
    flexDirection: "row",
    justifyContent: "center",
  },
  header: {
    fontSize: 32,
    backgroundColor: "black",
    color: "white",
    textAlign: "center",
  },
  title: {
    fontSize: 24,
    marginRight: 20,
    verticalAlign: "middle",
  },

  input: {
    backgroundColor: "white",
    marginTop: 20,
    borderRadius: 20,
    width: 320,
    height: 50,
    fontSize: 25,
    borderRadius: 15,
    padding: 10,
    textAlign: "center",
  },
  button: {
    backgroundColor: "#24788F",
    color: "white",
    paddingRight: 50,
    paddingTop: 10,
    width: 150,
    borderRadius: 20,
    marginTop: 20,
    height: 40,
    marginHorizontal: 100,
  },
  navBtn: {
    backgroundColor: "#481D24",
    width: 150,
    borderRadius: 20,
    marginTop: 20,
    padding: 5,
  },
  textDone: {
    color: "green",
    fontSize: 25,
    position: "absolute",
  },
  text: {
    color: "white",
    fontSize: 21,
    textAlign: "center",
  },
  textDel: {
    color: "white",
    fontSize: 15,
    position: "absolute",
  },
  textChecked: {
    color: "lightgreen",
    fontSize: 20,
    marginTop: 10,
  },
  card: {
    backgroundColor: "#481D24",
    marginTop: 20,
    width: 320,
    height: 50,
    borderRadius: 15,
    padding: 10,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    borderColor: "white",
  },
  circleDone: {
    width: 50,
    height: 30,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "black",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    backgroundColor: "#fff",
  },
  circleDel: {
    width: 50,
    height: 30,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "black",
    backgroundColor: "red",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  line: {
    width: 70,
    height: 3,
    backgroundColor: "green",
    position: "absolute",
    left: 110,
    top: 15,
  },
  inputContainer: {
    borderRadius: 20,
  },
});
